# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('places', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
