# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 3, 21, 4, 5, 506082), verbose_name='date joined'),
        ),
    ]
