# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-09 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 21, 18, 57, 528046), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='facebook_link'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='instagram_link'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='twitter_link'),
        ),
    ]
