# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20170131_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.TextField(default=datetime.datetime(2017, 1, 31, 20, 21, 42, 285977, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
