# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-05 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20170303_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('message', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
        ),
        migrations.RemoveField(
            model_name='venue',
            name='socialmedialinks',
        ),
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=b''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='facebook_link',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='instagram_link',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='twitter_link',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 5, 19, 35, 36, 701102), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=b''),
        ),
    ]
