# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-05 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20170305_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 5, 21, 43, 58, 449592), verbose_name='date joined'),
        ),
    ]
