# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20170309_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(),
        ),
    ]
