# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-14 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0004_auto_20170214_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attendeeNum', models.IntegerField()),
                ('date', models.DateField()),
                ('event_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Event_campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('accepted', models.BooleanField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Enquiry')),
            ],
        ),
    ]
