# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-09 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20170309_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
