# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-10 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_enquiry_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuebookerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User account details')),
            ],
        ),
        migrations.RemoveField(
            model_name='organisationadmin',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='organisationadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='venueadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='venueadmin',
            name='venue',
        ),
        migrations.DeleteModel(
            name='OrganisationAdmin',
        ),
        migrations.DeleteModel(
            name='VenueAdmin',
        ),
    ]
