# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_campaign',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Event_type'),
        ),
    ]
