# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20170325_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('event_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Event_campaign')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Venue')),
            ],
        ),
    ]
