# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20170328_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='quoteImage',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=b''),
        ),
    ]
