# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_venue_quoteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='quoteImage',
            field=models.ImageField(blank=True, default='/static/images/vblog.jpg', upload_to=b''),
        ),
    ]
