# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-08 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_auto_20170403_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='attendeeNum',
            field=models.IntegerField(verbose_name='Number of Attendees'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='venue',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='quoteImage',
            field=models.ImageField(blank=True, default='/static/images/vblogo.jpg', upload_to='', verbose_name='Image for Quote Emails'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
