# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_auto_20170408_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event_campaign',
            name='cost_per_capacity_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per person'),
        ),
    ]
