# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_auto_20170409_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateField(default='2017-04-09'),
        ),
    ]
