# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0017_auto_20170409_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactresponse',
            options={'verbose_name': 'My Contact Form Response', 'verbose_name_plural': 'My Contact Form Responses'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name': 'My Enquiry', 'verbose_name_plural': 'My Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='event_campaign',
            options={'verbose_name': 'My Event Campaign', 'verbose_name_plural': 'My Event Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'My Event Campaign Image', 'verbose_name_plural': "My Event Campaign's Images"},
        ),
        migrations.AlterModelOptions(
            name='organisationuser',
            options={'verbose_name': 'My Organisation User', 'verbose_name_plural': 'My Organisation Users'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'My Quote', 'verbose_name_plural': 'My Quotes'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'My Venue', 'verbose_name_plural': 'My Venues'},
        ),
        migrations.AlterModelOptions(
            name='venueimage',
            options={'verbose_name': 'My Venue Image', 'verbose_name_plural': "My Venue's Images"},
        ),
        migrations.AlterModelOptions(
            name='venueuser',
            options={'verbose_name': 'My Venue User', 'verbose_name_plural': 'My Venue Users'},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateField(default=b'2017-04-10'),
        ),
    ]
