# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-10 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0019_auto_20170410_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Organisation', 'verbose_name_plural': 'My Organisations'},
        ),
    ]
