# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0022_auto_20170411_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('BAR', 'Bar'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('CONFERENCE', 'Conference Center'), ('GALLERY', 'Gallery'), ('WAREHOUSE', 'Warehouse'), ('OUTSIDE', 'Outside'), ('ROOFTOP', 'Rooftop'), ('PRIVATE', 'Private Venue'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
