# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0023_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='company (optional)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('BAR', 'Bar'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('CONFERENCE', 'Conference Center'), ('GALLERY', 'Gallery'), ('WAREHOUSE', 'Warehouse'), ('OUTSIDE', 'Outside'), ('ROOFTOP', 'Rooftop'), ('PRIVATE', 'Private Venue'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
