# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0024_auto_20170412_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget')),
                ('comments', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('guests', models.IntegerField()),
                ('occasion', models.CharField(max_length=50)),
                ('received', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'My Leads',
            },
        ),
    ]
