# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-07 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
                ('capacity', models.IntegerField()),
                ('size', models.IntegerField(verbose_name='Size in Sq Feet')),
                ('venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Venue')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'My Rooms',
            },
        ),
    ]
